// Widgets
export const GET_WIDGET = 'GET_WIDGET'
export const ADD_WIDGET = 'ADD_WIDGET'
export const EDIT_WIDGET = 'EDIT_WIDGET'
export const GET_WIDGETS = 'GET_WIDGETS'
export const RECEIVE_WIDGETS = 'RECEIVE_WIDGETS'
export const GET_UPDATED_WIDGET = 'GET_UPDATED_WIDGET'

// Dashboards
export const ADD_NEW_WINDOW_TO_TOP_RIGHT = 'ADD_NEW_WINDOW_TO_TOP_RIGHT'
export const CREATE_DASHBOARD = 'CREATE_DASHBOARD'
export const UPDATE_DASHBOARD_NAME = 'UPDATE_DASHBOARD_NAME'
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD'
export const DASHBOARD_CHANGE = 'DASHBOARD_CHANGE'
export const GET_DASHBOARDS = 'GET_DASHBOARDS'
export const RECEIVE_DASHBOARDS = 'RECEIVE_DASHBOARDS'

// Datasources
export const GET_DATASOURCES = 'GET_DATASOURCES'
export const RECEIVE_DATASOURCES = 'RECEIVE_DATASOURCES'
