// Add Widgets
export const ADD_VIDEO = 'ADD_VIDEO'
export const ADD_LINE_GRAPH = 'ADD_LINE_GRAPH'
export const ADD_MAP = 'ADD_MAP'
export const WRITE_WIDGET_FORM = 'WRITE_WIDGET_FORM'

// Dashboard
export const ADD_TO_TOP_RIGHT = 'ADD_TO_TOP_RIGHT'
export const CREATE_DASHBOARD = 'CREATE_DASHBOARD'
export const UPDATE_DASHBOARD_NAME = 'UPDATE_DASHBOARD_NAME'
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD'
export const DASHBOARD_CHANGE = 'DASHBOARD_CHANGE'
export const GET_DASHBOARDS = 'GET_DASHBOARDS'
export const RECEIVE_DASHBOARDS = 'RECEIVE_DASHBOARDS'
export const SELECT_DASHBOARD = 'SELECT_DASHBOARD'
export const UNSELECT_DASHBOARD = 'UNSELECT_DASHBOARD'
